# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Track Review Project

on:
  workflow_run:
    workflows: [Trigger Review Project]
    types:
      - completed
  workflow_dispatch:

# Best Practice: Explicitly strip all top-level default permissions
permissions: {}

jobs:
  track_review_project:
    uses: ./.github/workflows/track-review-project.yaml
    secrets:
      PROJECT_ACTION_PAT: ${{ secrets.PROJECT_ACTION_PAT }}
    with:
      runner: "ubuntu-slim"
      project_org: "MetOffice"
      project_number: 376
    permissions:
      actions: read  # Required to check out code or parse files safely
      contents: read  # Required to read the upstream triggered workflow run artifact status
      pull-requests: write  # Required to add comments or update metadata on the PR
