# ------------------------------------------------------------------------------
# (c) Crown copyright Met Office. All rights reserved.
# The file LICENCE, distributed with this code, contains details of the terms
# under which the code may be used.
# ------------------------------------------------------------------------------

name: Lint
on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use for the job"
        required: false
        type: string
        default: "ubuntu-latest"
      timeout:
        description: "The maximum time in minutes the job can run for"
        required: false
        type: number
        default: 10
      ruff-version:
        description: "The ruff linter version to use"
        required: false
        type: string
        default: "0.15.0"
      source-path:
        description: "Path to source code directory to lint"
        required: false
        type: string
        default: "."
      fail-on-error:
        description: "Whether to fail the workflow on linting errors"
        required: false
        type: boolean
        default: true

jobs:
  python-linting:
    name: Python
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Ruff over directory
        uses: astral-sh/ruff-action@v4.0.0
        with:
          version: ${{ inputs.ruff-version }}
          src: ${{ inputs.source-path }}
          checksum: b949a853b208b0f818a150fb06490487db585a15becaeda28483dd662939030a
        continue-on-error: ${{ !inputs.fail-on-error }}
